version: '3.1'

services:
  web:
      container_name: ${CONTAINER_PREFIX}_
      build: .
      volumes:
          - ./src:/src
      ports:
          - "${SERVICE_PORT}:80"
      entrypoint:
          - python
          - /src/app/main.py
      environment:
